// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnn8XYwFSiM4FYOZJWyXoi3yG8jIquN2Q',
    appId: '1:1026169310419:web:ea71c69d30a288712d5826',
    messagingSenderId: '1026169310419',
    projectId: 'chatapp-423',
    authDomain: 'chatapp-423.firebaseapp.com',
    databaseURL: 'https://chatapp-423-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-423.appspot.com',
    measurementId: 'G-CBS85ETY9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfOVwtSa4q5t2Erfw_-ZASGPmnpdEcOw',
    appId: '1:1026169310419:android:61af19a56168452f2d5826',
    messagingSenderId: '1026169310419',
    projectId: 'chatapp-423',
    databaseURL: 'https://chatapp-423-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrr8EOq5RM7TYjMnNVWH6YtMxdAUn6sME',
    appId: '1:1026169310419:ios:d23037d0d2ee90252d5826',
    messagingSenderId: '1026169310419',
    projectId: 'chatapp-423',
    databaseURL: 'https://chatapp-423-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-423.appspot.com',
    iosClientId: '1026169310419-dof1bm7n4o5c2phno2223bcev74fle9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrr8EOq5RM7TYjMnNVWH6YtMxdAUn6sME',
    appId: '1:1026169310419:ios:d23037d0d2ee90252d5826',
    messagingSenderId: '1026169310419',
    projectId: 'chatapp-423',
    databaseURL: 'https://chatapp-423-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-423.appspot.com',
    iosClientId: '1026169310419-dof1bm7n4o5c2phno2223bcev74fle9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
